[project]
name = "perch-analyzer"
version = "0.1.0"
description = "Program to build bioacoustics classifiers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
]
